import React, { createContext, useContext, useState } from 'react';

const translations = {
    pt: {
        hero_badge: "Porta de Entrada para o Desenvolvimento de Angola",
        hero_title_1: "Liderando a",
        hero_title_2: "Logística Oceânica",
        hero_title_3: "do Soyo para o Mundo",
        hero_desc: "Administramos com excelência, segurança e sustentabilidade os complexos portuários estratégicos do Zaire, provendo suporte vital para o comércio regional e a indústria petrolífera nacional.",
        hero_btn_explore: "Explorar Serviços",
        hero_btn_tracker: "Painel de Navios",
        hero_badge_1: "Hub Logístico e Comercial",
        slide1_title1: "Liderando a",
        slide1_title2: "Logística Oceânica",
        slide1_title3: "do Soyo para o Mundo",
        slide1_desc: "Administramos com excelência, segurança e sustentabilidade os complexos portuários estratégicos do Zaire, provendo suporte vital para o comércio regional e a indústria petrolífera nacional.",
        hero_badge_2: "Infraestrutura Energética Global",
        slide2_title1: "Terminal",
        slide2_title2: "Exportando Energia",
        slide2_desc: "Operações de águas profundas de alta tecnologia para o escoamento global de gás natural liquefeito, posicionando Angola na vanguarda do setor de gás mundial.",
        slide2_btn: "Conhecer Terminal",
        hero_badge_3: "Conectividade Regional Marítima",
        slide3_title1: "Terminal Fluvial",
        slide3_title2: "Integração de Fronteiras",
        slide3_desc: "Promovemos a mobilidade segura de passageiros e carga geral através da cabotagem fluvial e marítima regular, unindo regiões e estimulando o comércio local.",
        slide3_btn: "Ver Horários",
        quick_1_title: "Rastreamento e Escalas",
        quick_1_desc: "Consulte navios atracados e chegadas previstas no Soyo.",
        quick_2_title: "Terminal Fluvial (Ferry)",
        quick_2_desc: "Horários e tarifas da ligação marítimo-fluvial Soyo-Cabinda.",
        quick_3_title: "Regulamentos e Ética",
        quick_3_desc: "Aceda à legislação e código de ética da empresa pública.",
        quick_4_title: "Suporte e Contactos",
        quick_4_desc: "Entre em contacto direto com a nossa equipa administrativa.",
        stat_terminals: "Terminais Operativos",
        stat_depth: "Calado no Canal",
        stat_cargo: "Ton. de Carga Anual",
        stat_ships: "Navios Anuais",
        about_tag: "A Instituição",
        about_title: "Quem Somos",
        tab_name_company: "Empresa Portuária do Soyo",
        tab_name_history: "A nossa História",
        tab_name_pca: "Mensagem do PCA",
        tab_name_board: "Conselho de Administração",
        company_title: "Comprometidos com o Futuro Marítimo",
        company_p1: "A Empresa Portuária do Soyo, E.P. (EPS-EP) é uma pessoa colectiva pública de direito angolano, criada através do Decreto Conjunto n.º 65/79 de 28 de Dezembro. Atuamos sob a tutela do Ministério dos Transportes e somos responsáveis pela administração, coordenação, fiscalização e exploração económica das infraestruturas e terminais portuários sob nossa jurisdição.",
        company_p2: "Nossa missão consiste em prover serviços de excelência para a navegação e movimentação de cargas, atuando de forma alinhada com as melhores práticas de sustentabilidade ambiental, impulsionando a economia do país e fortalecendo a segurança de nossas águas e instalações.",
        val_safety_title: "Segurança Máxima",
        val_safety_desc: "Garantia absoluta na proteção das tripulações, cargas e instalações.",
        val_eff_title: "Eficiência Operacional",
        val_eff_desc: "Tecnologia e agilidade para reduzir custos e prazos de atracação.",
        val_sust_title: "Sustentabilidade",
        val_sust_desc: "Preservação ambiental das áreas costeiras e do rio Congo.",
        hist_1_title: "Fundação Oficial",
        hist_1_desc: "A instituição é oficialmente constituída em 28 de Dezembro pelo Decreto Conjunto n.º 65/79, para organizar a atividade marítima no Soyo, Zaire.",
        hist_2_title: "Apoio à Indústria Petrolífera",
        hist_2_desc: "A Base da Ilha do Kwanda surge como um forte complexo logístico dedicado às multinacionais do petróleo e gás natural, expandindo a infraestrutura portuária.",
        hist_3_title: "Era do Gás Natural (LNG)",
        hist_3_desc: "Início das operações de exportação do terminal Angola LNG, colocando o Soyo em uma posição de relevância energética mundial.",
        hist_4_title: "Modernização Digital",
        hist_4_desc: "Forte investimento em modernização digital, concessões estratégicas (ex: Sogester) e sistemas inteligentes de controle marítimo para aumentar a competitividade regional.",
        pca_role: "Presidente do Conselho de Administração",
        pca_message_1: "\"O Porto do Soyo desempenha um papel fulcral no desenvolvimento socioeconómico da Província do Zaire e de toda a República de Angola. O nosso foco estratégico reside na reestruturação e modernização tecnológica das nossas infraestruturas, garantindo eficiência de classe mundial para as petrolíferas e importadores comerciais.\"",
        pca_message_2: "\"Procuramos criar pontes entre a inovação digital, a descarbonização das operações marítimas e a capacitação contínua do nosso capital humano. Trabalhamos diariamente para consolidar o Soyo como um porto competitivo, seguro, eficiente e um orgulho nacional no panorama portuário internacional.\"",
        board_title: "Liderança e Governança",
        board_pca: "Presidente do Conselho de Administração (PCA)",
        board_admin_exec: "Administrador Executivo (Finanças, RH e TI)",
        board_admin_non_exec: "Administrador Não Executivo",
        services_tag: "O que fazemos",
        services_title: "Serviços Portuários",
        serv_1_title: "Pilotagem e Praticagem",
        serv_1_short: "Condução segura de navios na foz do rio Congo e canais de acesso com práticos certificados.",
        serv_2_title: "Reboque e Amarração",
        serv_2_short: "Manobras de atracação e desatracação suportadas por rebocadores de alta capacidade tratora (Bollard Pull).",
        serv_3_title: "Movimentação de Cargas",
        serv_3_short: "Carga e descarga de contentores, carga geral e especializada com alta tecnologia e segurança.",
        serv_4_title: "Armazenagem e Logística",
        serv_4_short: "Instalações amplas para armazenamento coberto e a céu aberto, sob forte vigilância e controle digital.",
        serv_5_title: "Transporte Fluvial de Passageiros",
        serv_5_short: "Ligação de cabotagem fluvial de passageiros e viaturas entre o Soyo e Cabinda.",
        serv_6_title: "Apoio à Indústria Offshore",
        serv_6_short: "Base logística integrada (Ilha do Kwanda) e suporte logístico para a exploração de petróleo e gás.",
        serv_more: "Saber mais",
        modal_contact: "Requisitar Serviço",
        terminals_tag: "Nossa Infraestrutura",
        terminals_title: "Terminais Portuários",
        t_draft: "Calado Máximo",
        t_berths: "Comprimento de Cais",
        t_operator: "Operador / Gestor",
        t_cargo: "Principal Carga",
        ops_tag: "Operações em Tempo Real",
        ops_title: "Painel de Tráfego & Clima",
        weather_title: "Clima no Porto (Soyo)",
        weather_cond: "Parcialmente Nublado",
        w_wind: "Vento",
        w_tide: "Maré",
        w_vis: "Visibilidade",
        update_live: "Atualizado ao vivo",
        tracker_title: "Controlo de Navios",
        tracker_simulate: "Simular Entrada de Navio",
        leg_tag: "Transparência e Conduta",
        leg_title: "Legislação e Ética",
        leg_card1_title: "Legislação Portuária",
        leg_card1_desc: "Aceda às normas, regulamentos, decretos presidenciais e portarias governamentais vigentes que regulam e fiscalizam o tráfego e as operações de marinha mercante e mercadorias no Porto do Soyo.",
        leg_card2_title: "Código de Ética e Conduta",
        leg_card2_desc: "Consulte as diretrizes e regras comportamentais dos colaboradores e parceiros da Empresa Portuária do Soyo E.P. Fomentamos transparência, integridade administrativa e responsabilidade profissional.",
        leg_view: "Visualizar Documento",
        pdf_down: "Descarregar PDF",
        contacts_tag: "Fale Connosco",
        contacts_title: "Contactos e Suporte",
        contacts_h3: "Sede Administrativa",
        contacts_p: "Estamos prontos para atendê-lo e fornecer suporte sobre atracação, taxas, tráfego de passageiros ou parcerias logísticas.",
        c_addr: "Endereço",
        c_email: "E-mail Corporativo",
        c_phone: "Telefone / Apoio",
        c_hours: "Horário de Atendimento",
        c_hours_val: "Segunda a Sexta: 08:00 - 15:30 (Terminais: 24/7)",
        form_title: "Enviar Mensagem",
        form_name: "Nome Completo",
        form_email: "E-mail Corporativo",
        form_sub: "Assunto / Motivo",
        form_msg: "Escreva sua mensagem...",
        form_btn: "Enviar Mensagem",
        map_title: "Localização Estratégica",
        map_desc: "Foz do Rio Congo, Atlântico Sul",
        footer_about: "Empresa Portuária do Soyo E.P. Administrando caminhos marítimos e apoiando o desenvolvimento energético e logístico de Angola com eficiência e transparência.",
        footer_links: "Links Rápidos",
        footer_inst: "Governo",
        f_link_home: "Início",
        f_link_about: "Quem Somos",
        f_link_serv: "Serviços",
        f_link_term: "Terminais",
        f_link_track: "Painel de Operações",
        f_link_leg: "Legislação e Ética",
        f_link_cont: "Contactos de Apoio",
        f_copy: "Todos os direitos reservados."
    },
    en: {
        hero_badge: "Gateway to the Development of Angola",
        hero_title_1: "Leading",
        hero_title_2: "Ocean Logistics",
        hero_title_3: "from Soyo to the World",
        hero_desc: "We manage Zaire's strategic port complexes with excellence, safety, and sustainability, providing vital support for regional commerce and the national oil industry.",
        hero_btn_explore: "Explore Services",
        hero_btn_tracker: "Vessel Panel",
        hero_badge_1: "Logistics & Commercial Hub",
        slide1_title1: "Leading",
        slide1_title2: "Ocean Logistics",
        slide1_title3: "from Soyo to the World",
        slide1_desc: "We manage Zaire's strategic port complexes with excellence, safety, and sustainability, providing vital support for regional commerce and the national oil industry.",
        hero_badge_2: "Global Energy Infrastructure",
        slide2_title1: "Terminal",
        slide2_title2: "Exporting Energy",
        slide2_desc: "High-tech deepwater operations for global Liquefied Natural Gas (LNG) export, positioning Angola at the forefront of the global gas sector.",
        slide2_btn: "Explore Terminal",
        hero_badge_3: "Maritime Regional Connectivity",
        slide3_title1: "Fluvial Terminal",
        slide3_title2: "Border Integration",
        slide3_desc: "We promote safe mobility for passengers and general cargo through regular river and sea cabotage, joining regions and boosting local commerce.",
        slide3_btn: "View Timetable",
        quick_1_title: "Tracking & Schedules",
        quick_1_desc: "Check docked vessels and scheduled arrivals in Soyo.",
        quick_2_title: "Fluvial Terminal (Ferry)",
        quick_2_desc: "Schedules and fares for the Soyo-Cabinda ferry connection.",
        quick_3_title: "Regulations & Ethics",
        quick_3_desc: "Access the public company's legislation and code of ethics.",
        quick_4_title: "Support & Contacts",
        quick_4_desc: "Get in direct contact with our administrative team.",
        stat_terminals: "Operating Terminals",
        stat_depth: "Channel Draft",
        stat_cargo: "Annual Cargo Tons",
        stat_ships: "Annual Vessels",
        about_tag: "The Institution",
        about_title: "About Us",
        tab_name_company: "Soyo Port Authority",
        tab_name_history: "Our History",
        tab_name_pca: "Chairman's Message",
        tab_name_board: "Board of Directors",
        company_title: "Committed to the Maritime Future",
        company_p1: "The Empresa Portuária do Soyo, E.P. (EPS-EP) is an Angolan public corporate entity, established by Joint Decree No. 65/79 of December 28. Operating under the supervision of the Ministry of Transport, we are responsible for the administration, coordination, inspection, and economic exploitation of the port infrastructures and terminals under our jurisdiction.",
        company_p2: "Our mission is to provide excellent services for navigation and cargo handling, working in alignment with the best environmental sustainability practices, boosting the country's economy, and strengthening the security of our waters and facilities.",
        val_safety_title: "Maximum Safety",
        val_safety_desc: "Absolute guarantee in protecting crews, cargo, and facilities.",
        val_eff_title: "Operational Efficiency",
        val_eff_desc: "Technology and agility to reduce costs and docking times.",
        val_sust_title: "Sustainability",
        val_sust_desc: "Environmental preservation of coastal areas and the Congo River.",
        hist_1_title: "Official Foundation",
        hist_1_desc: "The institution is officially constituted on December 28 by Joint Decree No. 65/79, to organize maritime activity in Soyo, Zaire.",
        hist_2_title: "Support for the Oil Industry",
        hist_2_desc: "The Kwanda Island Base emerges as a strong logistical complex dedicated to oil and gas multinationals, expanding port infrastructure.",
        hist_3_title: "Natural Gas Era (LNG)",
        hist_3_desc: "Start of export operations of the Angola LNG terminal, putting Soyo in a position of global energy relevance.",
        hist_4_title: "Digital Modernization",
        hist_4_desc: "Strong investment in digital modernization, strategic concessions (e.g. Sogester), and intelligent maritime control systems to increase regional competitiveness.",
        pca_role: "Chairman of the Board of Directors",
        pca_message_1: "\"The Port of Soyo plays a central role in the socioeconomic development of Zaire Province and the entire Republic of Angola. Our strategic focus lies in restructuring and technologically modernizing our infrastructure, ensuring world-class efficiency for oil companies and commercial importers.\"",
        pca_message_2: "\"We seek to build bridges between digital innovation, decarbonization of maritime operations, and continuous training of our human capital. We work daily to consolidate Soyo as a competitive, safe, and efficient port, and a source of national pride on the international port scene.\"",
        board_title: "Leadership and Governance",
        board_pca: "Chairman of the Board (PCA)",
        board_admin_exec: "Executive Director (Finance, HR & IT)",
        board_admin_non_exec: "Non-Executive Director",
        services_tag: "What we do",
        services_title: "Port Services",
        serv_1_title: "Pilotage and Navigation",
        serv_1_short: "Safe guiding of vessels in the Congo River mouth and access channels by certified pilots.",
        serv_2_title: "Tugboat and Mooring",
        serv_2_short: "Berthing and unberthing maneuvers supported by modern tugboats with high Bollard Pull capacity.",
        serv_3_title: "Cargo Handling",
        serv_3_short: "Loading and unloading of containers, general and specialized cargo with high technology and safety.",
        serv_4_title: "Storage and Logistics",
        serv_4_short: "Ample facilities for covered and open-air storage, under tight security and digital control.",
        serv_5_title: "River Passenger Transport",
        serv_5_short: "Regular river cabotage connection for passengers and vehicles between Soyo and Cabinda.",
        serv_6_title: "Offshore Industry Support",
        serv_6_short: "Integrated logistics base (Kwanda Island) and supply support for oil and gas exploration.",
        serv_more: "Learn more",
        modal_contact: "Request Service",
        terminals_tag: "Our Infrastructure",
        terminals_title: "Port Terminals",
        t_draft: "Maximum Draft",
        t_berths: "Berth Length",
        t_operator: "Operator / Manager",
        t_cargo: "Primary Cargo",
        ops_tag: "Real-Time Operations",
        ops_title: "Traffic & Weather Panel",
        weather_title: "Port Weather (Soyo)",
        weather_cond: "Partly Cloudy",
        w_wind: "Wind",
        w_tide: "Tide",
        w_vis: "Visibility",
        update_live: "Updated live",
        tracker_title: "Vessel Control",
        tracker_simulate: "Simulate Vessel Entry",
        leg_tag: "Transparency & Conduct",
        leg_title: "Legislation & Ethics",
        leg_card1_title: "Port Legislation",
        leg_card1_desc: "Access the laws, regulations, presidential decrees, and government ordinances in force regulating and supervising merchant shipping and goods traffic in the Port of Soyo.",
        leg_card2_title: "Code of Ethics & Conduct",
        leg_card2_desc: "Check the behavior guidelines and rules for employees and partners of Empresa Portuária do Soyo E.P. We promote transparency, administrative integrity, and professional responsibility.",
        leg_view: "View Document",
        pdf_down: "Download PDF",
        contacts_tag: "Contact Us",
        contacts_title: "Contacts & Support",
        contacts_h3: "Administrative Head Office",
        contacts_p: "We are ready to assist you and provide support regarding docking, fees, passenger traffic, or logistics partnerships.",
        c_addr: "Address",
        c_email: "Corporate Email",
        c_phone: "Phone / Support",
        c_hours: "Office Hours",
        c_hours_val: "Monday to Friday: 08:00 - 15:30 (Terminals: 24/7)",
        form_title: "Send Message",
        form_name: "Full Name",
        form_email: "Corporate Email",
        form_sub: "Subject / Reason",
        form_msg: "Write your message...",
        form_btn: "Send Message",
        map_title: "Strategic Location",
        map_desc: "Congo River Mouth, South Atlantic",
        footer_about: "Empresa Portuária do Soyo E.P. Managing maritime pathways and supporting Angola's energy and logistic development with efficiency and transparency.",
        footer_links: "Quick Links",
        footer_inst: "Government",
        f_link_home: "Home",
        f_link_about: "About Us",
        f_link_serv: "Services",
        f_link_term: "Terminals",
        f_link_track: "Operations Panel",
        f_link_leg: "Legislation & Ethics",
        f_link_cont: "Support Contacts",
        f_copy: "All rights reserved."
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('pt');

    const t = (key) => {
        return translations[lang][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => useContext(LanguageContext);
