import React, { createContext, useContext, useState } from 'react';

const translations = {
    pt: {
        hero_badge: "O Motor do Desenvolvimento Angolano",
        hero_title_1: "Conectando o",
        hero_title_2: "Soyo ao Mundo",
        hero_desc: "Excelência e inovação na gestão do complexo portuário do Zaire. A força motriz por trás da expansão do comércio regional e suporte logístico de ponta para a indústria energética global.",
        hero_btn_explore: "Explorar Serviços",
        hero_btn_tracker: "Acompanhar Navios",
        hero_badge_1: "Epicentro Logístico & Comercial",
        slide1_title1: "Conectando o",
        slide1_title2: "Soyo ao Mundo",
        slide1_desc: "Excelência e inovação na gestão do complexo portuário do Zaire. A força motriz por trás da expansão do comércio regional e suporte logístico de ponta para a indústria energética global.",
        hero_badge_2: "Polo Energético Global",
        slide2_title1: "Terminal de GNL",
        slide2_title2: "Energizando o Planeta",
        slide2_desc: "Infraestrutura de águas profundas equipada com tecnologia avançada, vital para a exportação de gás natural e consolidação de Angola como potência energética mundial.",
        slide2_btn: "Conhecer Terminal",
        hero_badge_3: "Integração Regional Estratégica",
        slide3_title1: "Terminal Fluvial",
        slide3_title2: "Unindo Fronteiras",
        slide3_desc: "Garantimos o transporte seguro e ágil de passageiros e mercadorias numa rede fluvio-marítima estruturada, impulsionando a mobilidade e o desenvolvimento socioeconómico local.",
        slide3_btn: "Ver Horários",
        quick_1_title: "Tráfego e Atracações",
        quick_1_desc: "Acompanhamento em tempo real de operações e previsão rigorosa de chegadas.",
        quick_2_title: "Mobilidade Fluvial",
        quick_2_desc: "Rotas, tarifas e horários atualizados da travessia estratégica Soyo-Cabinda.",
        quick_3_title: "Governança e Ética",
        quick_3_desc: "Acesso transparente às regulamentações e ao rigoroso código de conduta.",
        quick_4_title: "Suporte Corporativo",
        quick_4_desc: "Atendimento especializado e direto com a nossa equipa de operações.",
        stat_terminals: "Terminais de Alta Performance",
        stat_depth: "Calado Operacional Máximo",
        stat_cargo: "Volume de Carga (Ton/Ano)",
        stat_ships: "Embarcações Atendidas (Ano)",
        about_tag: "A Nossa Essência",
        about_title: "Quem Somos",
        tab_name_company: "Empresa Portuária do Soyo",
        tab_name_history: "A Nossa Trajetória",
        tab_name_pca: "Mensagem do PCA",
        tab_name_board: "Conselho de Administração",
        company_title: "Liderança no Setor Marítimo e Logístico",
        company_p1: "A Empresa Portuária do Soyo, E.P. (EPS-EP) é uma entidade pública de excelência, constituída pelo Decreto Conjunto n.º 65/79. Sob a tutela do Ministério dos Transportes, assumimos o papel crucial de administrar, fiscalizar e otimizar as infraestruturas portuárias na estratégica região do Zaire.",
        company_p2: "Movidos pela inovação e por um firme compromisso com a sustentabilidade, entregamos soluções logísticas e marítimas de classe mundial. Mais do que movimentar cargas, impulsionamos a competitividade nacional e asseguramos o fluxo ininterrupto da economia angolana.",
        val_safety_title: "Segurança Inegociável",
        val_safety_desc: "Rigor absoluto na proteção de recursos humanos, ativos e operações complexas.",
        val_eff_title: "Alta Performance",
        val_eff_desc: "Agilidade suportada por tecnologia de ponta para otimizar tempo e recursos operacionais.",
        val_sust_title: "Visão Sustentável",
        val_sust_desc: "Compromisso duradouro com a preservação do ecossistema costeiro e do majestoso Rio Congo.",
        hist_1_title: "A Fundação",
        hist_1_desc: "Criação oficial da instituição a 28 de Dezembro, marcando o início da estruturação marítima profissional no município do Soyo.",
        hist_2_title: "Impulso Petrolífero",
        hist_2_desc: "A Base do Kwanda consolida-se como um complexo logístico fundamental, servindo as maiores multinacionais do setor de Oil & Gas.",
        hist_3_title: "A Era do GNL",
        hist_3_desc: "Inauguração das exportações do terminal Angola LNG, inserindo o Porto do Soyo na vanguarda da geopolítica energética global.",
        hist_4_title: "Transformação Digital",
        hist_4_desc: "Integração de sistemas inteligentes de gestão e modernização tecnológica contínua, elevando os padrões de competitividade do porto.",
        pca_role: "Presidente do Conselho de Administração",
        pca_message_1: "\"O Porto do Soyo é muito mais que um ponto de trânsito; é um hub vital para o desenvolvimento económico de Angola. Direcionamos os nossos investimentos para a inovação tecnológica e reestruturação infraestrutural, oferecendo eficiência inquestionável aos nossos parceiros e operadores globais.\"",
        pca_message_2: "\"A nossa visão baseia-se na criação de sinergias entre a transição digital, a sustentabilidade ambiental e a valorização do nosso talento humano. Trabalhamos todos os dias para erguer um porto cada vez mais ágil, seguro e competitivo—um orgulho para a nação no cenário marítimo internacional.\"",
        board_title: "Liderança e Governança",
        board_pca: "Presidente do Conselho de Administração (PCA)",
        board_admin_exec: "Administrador Executivo (Finanças, RH e TI)",
        board_admin_non_exec: "Administrador Não Executivo",
        services_tag: "O Nosso Portfólio",
        services_title: "Soluções Portuárias",
        serv_1_title: "Pilotagem Especializada",
        serv_1_short: "Navegação segura em águas complexas e canais do Rio Congo, conduzida por práticos altamente qualificados.",
        serv_2_title: "Reboque de Precisão",
        serv_2_short: "Apoio vital em manobras portuárias com rebocadores de última geração e elevada força de tração.",
        serv_3_title: "Movimentação de Cargas",
        serv_3_short: "Gestão inteligente de contentores e carga especializada, assegurando rapidez e integridade das mercadorias.",
        serv_4_title: "Logística Integrada",
        serv_4_short: "Áreas de armazenamento monitorizadas e parques de carga operados sob rigoroso controlo digital.",
        serv_5_title: "Mobilidade Fluvial",
        serv_5_short: "Ligação eficiente e segura para passageiros e veículos na vital travessia de cabotagem Soyo-Cabinda.",
        serv_6_title: "Suporte Offshore Premium",
        serv_6_short: "Infraestrutura logística de base e serviços dedicados exclusivamente à exigente indústria de petróleo e gás.",
        serv_more: "Detalhes do Serviço",
        modal_contact: "Solicitar Cotação",
        terminals_tag: "Infraestrutura de Ponta",
        terminals_title: "Terminais Especializados",
        t_draft: "Calado Máximo",
        t_berths: "Cais Atracável",
        t_operator: "Gestão Operacional",
        t_cargo: "Especialidade",
        ops_tag: "Monitorização Ativa",
        ops_title: "Centro de Controlo & Tráfego",
        weather_title: "Condições Atmosféricas",
        weather_cond: "Parcialmente Nublado",
        w_wind: "Vento",
        w_tide: "Maré",
        w_vis: "Visibilidade",
        update_live: "Dados em Tempo Real",
        tracker_title: "Painel de Atracações",
        tracker_simulate: "Acompanhamento Virtual",
        leg_tag: "Rigor e Integridade",
        leg_title: "Marco Regulatório",
        leg_card1_title: "Base Legal Portuária",
        leg_card1_desc: "Acesso integral aos diplomas, decretos e regulamentações do Estado que orientam as atividades marítimas comerciais e a exploração do perímetro portuário.",
        leg_card2_title: "Código de Conduta",
        leg_card2_desc: "Princípios orientadores da nossa cultura organizacional. Valorizamos a transparência corporativa, a ética nos negócios e a responsabilidade social em cada operação.",
        leg_view: "Ler Documento",
        pdf_down: "Download (PDF)",
        contacts_tag: "Linha Direta",
        contacts_title: "Fale com os Nossos Especialistas",
        contacts_h3: "Sede Administrativa (Soyo)",
        contacts_p: "A nossa equipa está permanentemente disponível para agilizar as suas operações logísticas, clarificar procedimentos e estruturar parcerias de sucesso.",
        c_addr: "Endereço Institucional",
        c_email: "E-mail Corporativo",
        c_phone: "Linha de Atendimento",
        c_hours: "Horário de Funcionamento",
        c_hours_val: "Serviços Administrativos: 08:00 - 15:30 | Operações Portuárias: 24/7",
        form_title: "Envie-nos uma Mensagem",
        form_name: "Nome da Entidade / Responsável",
        form_email: "Endereço de E-mail Corporativo",
        form_sub: "Natureza do Contacto",
        form_msg: "Descreva a sua solicitação em detalhe...",
        form_btn: "Submeter Formulário",
        map_title: "Posicionamento Geoestratégico",
        map_desc: "Foz do Rio Congo, Atlântico Sul",
        footer_about: "Empresa Portuária do Soyo E.P. Gerindo rotas marítimas estratégicas e catalisando o progresso energético e logístico de Angola com absoluta eficiência, inovação e rigor corporativo.",
        footer_links: "Acesso Rápido",
        footer_inst: "Governo e Instituições",
        f_link_home: "Início",
        f_link_about: "Nossa Essência",
        f_link_serv: "Portfólio de Serviços",
        f_link_term: "Nossos Terminais",
        f_link_track: "Painel Operacional",
        f_link_leg: "Governança Corporativa",
        f_link_cont: "Atendimento e Suporte",
        f_copy: "Todos os direitos reservados."
    },
    en: {
        hero_badge: "The Engine of Angolan Development",
        hero_title_1: "Connecting",
        hero_title_2: "Soyo to the World",
        hero_desc: "Excellence and innovation in managing Zaire's port complex. The driving force behind regional trade expansion and cutting-edge logistical support for the global energy industry.",
        hero_btn_explore: "Explore Services",
        hero_btn_tracker: "Track Vessels",
        hero_badge_1: "Logistics & Commercial Hub",
        slide1_title1: "Connecting",
        slide1_title2: "Soyo to the World",
        slide1_desc: "Excellence and innovation in managing Zaire's port complex. The driving force behind regional trade expansion and cutting-edge logistical support for the global energy industry.",
        hero_badge_2: "Global Energy Hub",
        slide2_title1: "LNG Terminal",
        slide2_title2: "Energizing the Planet",
        slide2_desc: "Advanced deep-water infrastructure essential for LNG exports, consolidating Angola's position as a global energy powerhouse.",
        slide2_btn: "Discover Terminal",
        hero_badge_3: "Strategic Regional Integration",
        slide3_title1: "Fluvial Terminal",
        slide3_title2: "Bridging Borders",
        slide3_desc: "Ensuring the safe and agile transport of passengers and goods through a structured river-sea network, boosting local mobility and socioeconomic development.",
        slide3_btn: "View Timetable",
        quick_1_title: "Traffic & Berthing",
        quick_1_desc: "Real-time monitoring of port operations and accurate vessel arrival forecasts.",
        quick_2_title: "Fluvial Mobility",
        quick_2_desc: "Updated routes, fares, and schedules for the strategic Soyo-Cabinda crossing.",
        quick_3_title: "Governance & Ethics",
        quick_3_desc: "Transparent access to institutional regulations and strict corporate codes of conduct.",
        quick_4_title: "Corporate Support",
        quick_4_desc: "Specialized, direct communication channels with our operational and administrative teams.",
        stat_terminals: "High-Performance Terminals",
        stat_depth: "Maximum Operational Draft",
        stat_cargo: "Cargo Volume (Tons/Year)",
        stat_ships: "Vessels Serviced (Year)",
        about_tag: "Our Core Identity",
        about_title: "About Us",
        tab_name_company: "Soyo Port Authority",
        tab_name_history: "Our Trajectory",
        tab_name_pca: "Chairman's Message",
        tab_name_board: "Board of Directors",
        company_title: "Leadership in the Maritime and Logistics Sector",
        company_p1: "Empresa Portuária do Soyo, E.P. (EPS-EP) is a premier public entity established by Joint Decree No. 65/79. Supervised by the Ministry of Transport, we play the crucial role of managing, regulating, and optimizing port infrastructure in the strategic Zaire region.",
        company_p2: "Driven by innovation and an unwavering commitment to sustainability, we deliver world-class maritime and logistics solutions. Beyond moving cargo, we boost national competitiveness and ensure the uninterrupted flow of the Angolan economy.",
        val_safety_title: "Non-Negotiable Safety",
        val_safety_desc: "Absolute rigor in protecting human resources, assets, and complex operations.",
        val_eff_title: "High Performance",
        val_eff_desc: "Agility backed by state-of-the-art technology to optimize time and operational resources.",
        val_sust_title: "Sustainable Vision",
        val_sust_desc: "Enduring commitment to preserving the coastal ecosystem and the majestic Congo River.",
        hist_1_title: "The Foundation",
        hist_1_desc: "Official establishment of the institution on December 28, marking the dawn of professional maritime organization in Soyo.",
        hist_2_title: "The Oil & Gas Impulse",
        hist_2_desc: "The Kwanda Base solidifies itself as a fundamental logistics complex serving the major multinationals in the Oil & Gas sector.",
        hist_3_title: "The LNG Era",
        hist_3_desc: "Inauguration of exports from the Angola LNG terminal, placing the Port of Soyo at the forefront of global energy geopolitics.",
        hist_4_title: "Digital Transformation",
        hist_4_desc: "Integration of smart management systems and continuous technological modernization, raising the port's competitive standards.",
        pca_role: "Chairman of the Board of Directors",
        pca_message_1: "\"The Port of Soyo is much more than a transit point; it is a vital hub for Angola's economic development. We focus our investments on technological innovation and infrastructure restructuring, delivering unquestionable efficiency to our partners and global operators.\"",
        pca_message_2: "\"Our vision relies on creating synergies between the digital transition, environmental sustainability, and the empowerment of our human talent. We work daily to build an increasingly agile, safe, and competitive port—a source of national pride on the international maritime stage.\"",
        board_title: "Leadership and Governance",
        board_pca: "Chairman of the Board of Directors (PCA)",
        board_admin_exec: "Executive Director (Finance, HR & IT)",
        board_admin_non_exec: "Non-Executive Director",
        services_tag: "Our Portfolio",
        services_title: "Port Solutions",
        serv_1_title: "Specialized Pilotage",
        serv_1_short: "Safe navigation through complex waters and the Congo River channels, guided by highly qualified pilots.",
        serv_2_title: "Precision Towage",
        serv_2_short: "Vital support in port maneuvers with next-generation tugboats boasting exceptional bollard pull.",
        serv_3_title: "Cargo Handling",
        serv_3_short: "Smart management of containers and specialized cargo, ensuring speed and the integrity of goods.",
        serv_4_title: "Integrated Logistics",
        serv_4_short: "Monitored storage areas and freight yards operated under strict digital tracking and control.",
        serv_5_title: "Fluvial Mobility",
        serv_5_short: "An efficient and secure cabotage link for passengers and vehicles across the vital Soyo-Cabinda route.",
        serv_6_title: "Premium Offshore Support",
        serv_6_short: "Dedicated base infrastructure and tailored services exclusively supporting the demanding oil and gas industry.",
        serv_more: "Service Details",
        modal_contact: "Request a Quote",
        terminals_tag: "State-of-the-Art Infrastructure",
        terminals_title: "Specialized Terminals",
        t_draft: "Maximum Draft",
        t_berths: "Berth Capacity",
        t_operator: "Operational Management",
        t_cargo: "Primary Specialty",
        ops_tag: "Active Monitoring",
        ops_title: "Traffic & Control Center",
        weather_title: "Atmospheric Conditions",
        weather_cond: "Partly Cloudy",
        w_wind: "Wind",
        w_tide: "Tide",
        w_vis: "Visibility",
        update_live: "Real-Time Data",
        tracker_title: "Berthing Dashboard",
        tracker_simulate: "Virtual Tracking",
        leg_tag: "Rigor & Integrity",
        leg_title: "Regulatory Framework",
        leg_card1_title: "Legal Port Framework",
        leg_card1_desc: "Full access to state diplomas, decrees, and regulations that guide commercial maritime activities and operations within the port perimeter.",
        leg_card2_title: "Code of Conduct",
        leg_card2_desc: "The guiding principles of our organizational culture. We value corporate transparency, business ethics, and social responsibility in every operation.",
        leg_view: "Read Document",
        pdf_down: "Download (PDF)",
        contacts_tag: "Direct Line",
        contacts_title: "Speak with Our Experts",
        contacts_h3: "Administrative Headquarters (Soyo)",
        contacts_p: "Our team is permanently available to expedite your logistics operations, clarify procedures, and build successful partnerships.",
        c_addr: "Institutional Address",
        c_email: "Corporate Email",
        c_phone: "Support Hotline",
        c_hours: "Operating Hours",
        c_hours_val: "Administrative Services: 08:00 - 15:30 | Port Operations: 24/7",
        form_title: "Send Us a Message",
        form_name: "Entity Name / Contact Person",
        form_email: "Corporate Email Address",
        form_sub: "Nature of Inquiry",
        form_msg: "Please describe your request in detail...",
        form_btn: "Submit Form",
        map_title: "Geostrategic Positioning",
        map_desc: "Congo River Mouth, South Atlantic",
        footer_about: "Empresa Portuária do Soyo E.P. Managing strategic maritime routes and catalyzing Angola's energy and logistics progress with absolute efficiency, innovation, and corporate rigor.",
        footer_links: "Quick Access",
        footer_inst: "Government & Institutions",
        f_link_home: "Home",
        f_link_about: "Our Identity",
        f_link_serv: "Service Portfolio",
        f_link_term: "Our Terminals",
        f_link_track: "Operational Dashboard",
        f_link_leg: "Corporate Governance",
        f_link_cont: "Service & Support",
        f_copy: "All rights reserved."
    }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('pt');

    const t = (key) => {
        return translations[lang][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useTranslation = () => useContext(LanguageContext);
